### ISSUE TITLE
vamp-gateway-agent not starting

### ISSUE THREAD

**Issue by michelroolvink** [magneticio/vamp-gateway-agent#12]
I downloaded the latest vamp-gateway-agent.
When starting the agent i am getting the following errors:

``` code
/opt/vamp/vamp-gateway-agent --logo=false --storeType=zookeeper --storeConnection=127.0.0.1:2181
```

``` code
15:18:13.618 main CRIT ==> No basic HAProxy configuration: /opt/vamp/haproxy.basic.cfg 
panic: No basic HAProxy configuration: /opt/vamp/haproxy.basic.cfg

goroutine 1 [running]:
github.com/op/go-logging.(*Logger).Panic(0x18bc8a00, 0x18b37f64, 0x3, 0x3)
        /home/travis/build/magneticio/vamp-dist/vamp-gateway-agent/target/go_path/src/github.com/op/go-logging/logger.go:182 +0x13b
main.main()
        /home/travis/build/magneticio/vamp-dist/vamp-gateway-agent/target/go_path/src/github.com/vamp-gateway-agent/main.go:74 +0x501

goroutine 6 [syscall]:
os/signal.loop()
        /home/travis/build/magneticio/vamp-dist/vamp-gateway-agent/target/go/src/os/signal/signal_unix.go:22 +0x1a
created by os/signal.init.1
        /home/travis/build/magneticio/vamp-dist/vamp-gateway-agent/target/go/src/os/signal/signal_unix.go:28 +0x36
```

Any hints

**Comment by dragoslav** [comment]
Hi @michelroolvink could you place https://github.com/magneticio/vamp-gateway-agent/blob/master/haproxy.basic.cfg to `/opt/vamp/` (or other location if you use `configurationPath` and `configurationBasicFile`)? It's something new, added recently to 0.8.3, we should update docs. Basically Vamp generated HAProxy conf (frontends/backends) will be appended to `haproxy.basic.cfg`, so you can use your own HAProxy conf as base.

**Comment by michelroolvink** [comment]
Thanx it seems to be working. I had to remove one line: "server-state-file /opt/vamp/haproxy_server_state" in the file because of an older version of haproxy.

**Comment by olafmol** [comment]
haproxy base config for 1.6.x can be found here: https://github.com/magneticio/vamp-gateway-agent/blob/master/docker/1.6.3/haproxy.basic.cfg
