### ISSUE TITLE
Investigate HAProxy reloads with Go 1.5/1.6 compiled binaries

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-gateway-agent#16]
https://github.com/magneticio/vamp-gateway-agent/commit/0a2f365b50d27243b05ea264ad063f89433def55#commitcomment-16796748
https://github.com/hashicorp/consul-template/issues/442

This may not be an issue since we already use Go 1.6 during development and will continue in the following releases starting from 0.9.0.

Still it is important to reproduce it with 1.5 and confirm it doesn't happen with 1.6.

**Comment by bbaptist** [comment]
I am testing out Vamp 0.8.5 in DC/OS 1.7. I am seeing this exact issue. I noticed that the pid directive specified in the haproxy.cfg is different than what the reload.sh script uses, not sure if that error might be related.
