### ISSUE TITLE
Hardcoded VAMP_PULSE_ELASTICSEARCH_URL

### ISSUE THREAD

**Issue by BauRo** [magneticio/vamp-gateway-agent#20]
since release 0.9.0 the docker container magneticio/vamp:0.9.0-dcos is searching on startup for: 

```
http://elasticsearch-executor.elasticsearch.mesos:9200
```

The should be overridden by the environment varibale 

```
"VAMP_PULSE_ELASTICSEARCH_URL": "http://elasticsearch.service.consul:9200" (in our case)
```

This is not happening so, the container wil not start the vamp application.
I guess it is somewhere hardcoded.

**Comment by dragoslav** [comment]
Moved to the main repo: https://github.com/magneticio/vamp/issues/708 and closing it here.

**Comment by dragoslav** [comment]
It is not enough to have `VAMP_PULSE_ELASTICSEARCH_URL` set, but also `VAMP_PERSISTENCE_DATABASE_ELASTICSEARCH_URL`. So if you use Vamp DC/OS image without overriding persistence configuration, URL for persistence will still be set to `http://elasticsearch-executor.elasticsearch.mesos:9200`.
