### ISSUE TITLE
Add health check

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-gateway-agent#21]
Something like `/health` and `200 response with body: OK` like https://www.airbnb.com/health
This should allow monitoring of VGA containers and restarting them if needed.

**Comment by harmw** [comment]
At wehkamp we're using the following block in haproxy.cfg:

```
frontend status
    bind *:81
    monitor-uri /status
```

**Comment by olafmol** [comment]
re-opening due to issue #35

**Comment by iamtew** [comment]
See https://github.com/magneticio/vamp-artifacts/commit/3dad31d5e8c33734d90e913578b0130cc69344ee
