### ISSUE TITLE
Supervisor and init system

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-gateway-agent#27]
For instance: https://github.com/Yelp/dumb-init
We need to run at least `confd` https://github.com/magneticio/vamp-gateway-agent/issues/7 and top/file beats https://github.com/magneticio/vamp-gateway-agent/issues/4

This is eventually applicable also to https://github.com/magneticio/vamp-workflow-agent

**Comment by iamtew** [comment]
`runit` seems like a better fit as it can manage multiple processes/services, and will restart if necessary.

- http://smarden.org/runit/
- https://github.com/peterbourgon/runsvinit

**Comment by iamtew** [comment]
Initial changes made under: 9c2ad1100d08648bfe83e286a73c905bdd7b5815
