### ISSUE TITLE
Define what minimal haproxy metrics we need to log 

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-gateway-agent#30]
currently we log all fields from HAproxy, at minimum we need 3 ('ft' (frontend id - based on gateway), 'Tt' (response time), 'ST' (status code)), we need to investigate if these are enough to log and what needs to be done to implement this.

**Comment by iamtew** [comment]
These are the required fields, additional information is being logged still although redundant logging has been fixed as mentioned in #23 

Closing as the required fields are being logged already.
