### ISSUE TITLE
Katana VGA's (v093 rc) don't show as healthy in DC/OS marathon UI

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-gateway-agent#35]
i believe they should have a health endpoint configured where DC/OS can check their 200 status so they show up as green/healthy in the DCOS marathon dashboard

**Comment by dragoslav** [comment]
https://github.com/magneticio/vamp-gateway-agent/issues/21#issuecomment-250536955

**Comment by iamtew** [comment]
See https://github.com/magneticio/vamp-artifacts/commit/3dad31d5e8c33734d90e913578b0130cc69344ee
