### ISSUE TITLE
[093rc/katana] Vamp Gateway Agent should exit gracefully on error

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-gateway-agent#36]
currently when VGA 093rc doesn't have key value path set, it keeps on looping the ascii art message in the stdout, it should fail gracefully after sending the error message.

**Comment by iamtew** [comment]
Part that needs to be updated: https://github.com/magneticio/vamp-gateway-agent/blob/master/files/etc/service/vamp-gateway-agent/run#L21-L24

**Comment by iamtew** [comment]
This won't happen when we control the start of the VGA, as those settings are required. See f2f96c87d67be044d0020d2b7f3c142bae647e52
