### ISSUE TITLE
VGA's spread ZK connects over multiple nodes

### ISSUE THREAD

**Issue by olafmol** [magneticio/vamp-gateway-agent#39]
currently our VGA's (and maybe also other Vamp components) only hit 1 specific ZK node (often zk-1) while there are multiple ZK nodes (typically 5). It would be good to investigate if spreading the connections over multiple ZK nodes increased performance/stability of the entire system. Supposedly a comma-delimited list of ZK nodes kan be passed for connection options.

**Comment by ItsMeijers** [comment]
Fixed by 118f3caf2126d51a5cbeeae8755c09be832bbdb2
