### ISSUE TITLE
is support zero down time reload haproxy?

### ISSUE THREAD

**Issue by bench87** [magneticio/vamp-gateway-agent#56]
I am testing connection fail how i keep request and change weight

but some connection fail, how can i zero down time reload? plz help

**Comment by olafmol** [comment]
Please try with the latest magneticio/vamp:0.9.5.6-dcos docker container, you can use this manual installation instruction:

https://vamp.io/documentation/installation/v0.9.5/dcos/#manual-install

by replacing the Vamp docker container from 0.9.5 to 0.9.5.6

Let me know how this works for you.

**Comment by bench87** [comment]
I have same issue with 0.9.5.6;; T_T,

**Comment by bench87** [comment]
hm... i tried to scale up cpu and memory, That was not reproduced.

**Comment by olafmol** [comment]
Could you describe the steps you do to reproduce this issue?

**Comment by bench87** [comment]
I try magneticio/vamp:0.9.5.6-dcos docker container you said, and two app server deployed and then 
I run simple python script like blow
`
import requests
from collections import defaultdict
result = defaultdict(lambda: 0)
for i in range(5000):
    print(i)
    r = requests.post('http://url', json={'a': 'a'})
    result[r.text] += 1

for k, v in result.items():
    print(k, v, flush=True)
`

and then I had to change the weight continuously with vamp gateway UI

when I run VGA with cpu 0.1 memory 128, I got error like blow

Traceback (most recent call last):
  File "req.py", line 6, in <module>
    r = requests.post('http://url', json={'a': 'a'})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

but If i run VGA with CPU 1 memory 512, that was not reproduced

**Comment by bench87** [comment]
no no even if GVA with CPU 1 memory 512, It was reproduced 
 T_T

**Comment by bench87** [comment]
@olafmol when I change haproxy reload parameter, It was not reproduced, -sf parameter do more gracefully reload

**Comment by olafmol** [comment]
@bench87 sounds good! We replaced -sf with -st at some point because we did encounter orphaned haproxy processes staying alive. So please check if you don't encounter multiple HAproxy processes when using -sf. Also we're bumping up to HAproxy 1.8 now, which should solve the "no dropped packets hot reloads" by itself (see https://www.haproxy.com/blog/truly-seamless-reloads-with-haproxy-no-more-hacks/) .

For safety you can make sure the HAproxy processes stay pinned to the same CPU core when deploying on multi-core machines.

**Comment by bench87** [comment]
@olafmol Thank you, Im gonna use haproxy with -sf and I also wait new release with haproxy 1.8
vamp is so good!
