### ISSUE TITLE
Consider using confd

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-gateway-agent#7]
https://github.com/kelseyhightower/confd
https://hub.docker.com/r/yaronr/haproxy-confd/

**Comment by rawmind0** [comment]
Early release of it. 
https://github.com/rawmind0/rancher-vamp-haproxy

TODO: send metrics to logstash or elasticsearch.
Pretend to do it with rsyslog, sending them to logstash or directly to elasticsearch. Help, thoughts, ideas??
